#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive

installpkg(){
    dpkg-query --status $1 >/dev/null || apt-get install -y $1
}

apt-get update
installpkg php5
installpkg php5-apcu
installpkg php5-mysql
installpkg php5-gearman
installpkg mysql-server
installpkg apache2-utils
installpkg apache2-suexec-custom
installpkg gearman-job-server
installpkg gearman-tools

echo "ServerName localhost" > /etc/apache2/conf-enabled/servername.conf
a2enmod suexec
a2dissite 000-default.conf
cp /tmp/001-talented.conf /etc/apache2/sites-available
a2ensite  001-talented.conf
service apache2 restart

curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
cd code
composer.phar --no-dev install
composer.phar dumpautoload -o
cd ..

bootstrapdb(){
    cat <<EOF | mysql -uroot
    DROP DATABASE IF EXISTS samtt;
    CREATE DATABASE samtt;
    USE samtt;
    CREATE TABLE mo (
      id int NOT NULL auto_increment,
      msisdn varchar(20),
      operatorid int,
      shortcodeid int,
      text varchar(255),
      auth_token varchar(60),
      created_at DATETIME NOT NULL,
      PRIMARY KEY(id)
    ) ;
EOF
}
bootstrapdb

echo 'Db created!'

chmod a+x /tmp/populate_db
populate_db() {
    /tmp/populate_db 10000000| mysql -u root samtt
}
populate_db

echo 'Db populated!'

createIndex() {
    echo 'CREATE INDEX `idx_created` ON `mo` (`created_at` ASC)'| mysql -u root samtt
}
createIndex

#warmup caches
